version: "3"


services:

    jupyter:
        build:
            context: .
            dockerfile: ./Dockerfile 
        ports:
            - 8888:8888
        volumes:
            - .:/data
            - /var/run/docker.sock:/var/run/docker.sock

