version: "3"


services:

    jupyter:
        build:
            context: .
            dockerfile: ./docker/Dockerfile 
        ports:
            - 8888:8888
        volumes:
            - .:/data
            - /var/run/docker.sock:/var/run/docker.sock   # Docker inside of docker! 
            - ../earthquake-recognition:/earthquake-recognition
        command: jupyter lab --notebook-dir=/ --ip='0.0.0.0' --allow-root --port=8888 --no-browser


